// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdjlvtpellathuwdmpsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhkamx2dHBlbGxhdGh1d2RtcHNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MDI5MzgsImV4cCI6MjA2NTA3ODkzOH0.XUhbVhHRjsrKpoYqNVXoUu4REzatZ3R-gqE-McmchjQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);