// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihxvadzdckdoufloansv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloeHZhZHpkY2tkb3VmbG9hbnN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDgxOTEsImV4cCI6MjA2OTIyNDE5MX0.DG9trcU_mwqudsBpr_dbk__1j1alpupCcNr9rI6iGsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});