
import React from 'react';
import { useIsMobile } from '@/hooks/use-mobile';
import MobileHeader from '@/components/MobileHeader';
import Navbar from '@/components/Navbar';
import { Card, CardContent } from '@/components/ui/card';
import { BookOpen, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';

const MarketAnalysis = () => {
  const isMobile = useIsMobile();

  return (
    <div className="flex flex-col min-h-screen">
      {isMobile ? (
        <MobileHeader title="Market Analysis" showBackButton />
      ) : (
        <Navbar />
      )}
      <main className={`flex-grow ${isMobile ? 'pt-0' : 'pt-14 md:pt-16'} px-4 py-6`}>
        <div className="max-w-3xl mx-auto">
          <h1 className="text-2xl font-bold mb-2">Market Analysis</h1>
          <p className="text-gray-600 mb-6">Master the techniques used by professionals to analyze market trends and make informed decisions.</p>
          
          <div className="space-y-8">
            <section>
              <h2 className="text-xl font-semibold mb-4">Fundamental Analysis</h2>
              <Card className="mb-6">
                <CardContent className="p-6">
                  <h3 className="text-lg font-medium mb-2">What is Fundamental Analysis?</h3>
                  <p className="text-gray-600 mb-4">
                    Fundamental analysis involves evaluating a security by examining related economic, financial, and other qualitative and quantitative factors. The goal is to determine the intrinsic value of an investment to identify whether it is overvalued or undervalued.
                  </p>
                  
                  <h3 className="text-lg font-medium mb-2">Key Metrics</h3>
                  <p className="text-gray-600 mb-4">
                    Important fundamental metrics include earnings per share (EPS), price-to-earnings ratio (P/E), price-to-book ratio (P/B), debt-to-equity ratio, and return on equity (ROE). These metrics provide insights into a company's financial health and valuation.
                  </p>
                </CardContent>
              </Card>
            </section>
            
            <section>
              <h2 className="text-xl font-semibold mb-4">Technical Analysis</h2>
              <Card className="mb-6">
                <CardContent className="p-6">
                  <h3 className="text-lg font-medium mb-2">What is Technical Analysis?</h3>
                  <p className="text-gray-600 mb-4">
                    Technical analysis is a method of evaluating securities by analyzing statistics generated by market activity, such as past prices and volume. Technical analysts do not attempt to measure a security's intrinsic value but instead use charts and other tools to identify patterns that can suggest future activity.
                  </p>
                  
                  <h3 className="text-lg font-medium mb-2">Common Indicators</h3>
                  <p className="text-gray-600">
                    Popular technical indicators include moving averages, relative strength index (RSI), moving average convergence divergence (MACD), and Bollinger Bands. These tools help traders identify trend directions, momentum, and potential reversal points.
                  </p>
                </CardContent>
              </Card>
            </section>
            
            <section>
              <h2 className="text-xl font-semibold mb-4">Next Steps</h2>
              <div className="flex items-center text-[#9b87f5]">
                <Link to="/education/retirement-planning" className="flex items-center hover:underline">
                  <span className="mr-1">Continue to Retirement Planning</span>
                  <ArrowRight className="h-4 w-4" />
                </Link>
              </div>
            </section>
          </div>
        </div>
      </main>
    </div>
  );
};

export default MarketAnalysis;
